### ISSUE TITLE
Configuration for time for tasks

### ISSUE THREAD

**Issue by jonnguye** [PacificBiosciences/HiFi-human-WGS-WDL#118]
I'm using an hpc slurm system to currently run this workflow and it works great, but my scheduler requires a time to be specified for each job. I'm currently setting a time in the higher level config that assigns the same time to all tasks, but was wondering if there is a way to configure it per task.

I'm currently running this through miniwdl.

Thanks

**Comment by williamrowell** [comment]
Because we're supporting this workflow on heterogenous compute and for variable sequencing-depth/sample-count, it's hard to predict how long each task should take for all of our users on their various compute platforms.

The longest tasks typically take ~3-5h for us on HPC with slurm, so if you set a universal limit of 6-8 hours, you should be covered.  If, in your experience, you find that some tasks reproducibly take much less time (e.g., `concat_vcf`, `bcftools`, `mosdepth`, `hificnv`, `paraphase`), you can provide a 'runtime. slurm_partition' and/or 'runtime.time_minutes' (assuming miniwdl-slurm plugin) for those tasks to get them scheduled on a different/faster partition.
