### ISSUE TITLE
Package all associated tools into one single docker image

### ISSUE THREAD

**Issue by Bin-Guan** [PacificBiosciences/HiFi-human-WGS-WDL#125]
When we tried the workflow in our HPC, it encountered multiple errors. One is "Error connecting to https://quay.io". Is it possible to package all necessary tools used in the workflow in a standalone docker? This might be much easier to set up for users. We're planning to buy the Revio so we hope the analyses will be seamless. 

Thanks for considering this feature.

**Comment by williamrowell** [comment]
Thanks for the suggestion.

By keeping these images separate, we can more easily update individual components without having to change the code for every task.  Also, some tools have incompatible dependencies, so building them into separate containers makes them easier to deploy.

I think it's likely that the problem you're seeing is caused by the inability of your HPC compute nodes to access the internet.  Consolidating into a single image would not solve this issue.  There are at least a few solutions:

- You can set up a private docker container repo within your HPC network, store copies of the containers that you will need for this workflow, and provide the url for this internal repo as `humanwgs.container_registry` in your inputs.json files.
- If you use miniwdl with singularity (for example, with the miniwdl-slurm plugin), images are downloaded and cached as .sif files on the head node (where the job was launched) and fetched from this cache when they are used.  Since login nodes are typically connected to the internet, this might work for you.
- If you use Cromwell, there's a tool called [singularity-permanent-cache](https://github.com/biowdl/singularity-permanent-cache) that caches images as .sif files.  You can use `singularity-permanent-cache` to download the containers from a node that can access the internet, then adjust cromwell.conf to use `singularity-permanent-cache` to lookup the file path for the containers.

If you're looking for help with any of this, please email support@pacb.com.

**Comment by clhappyjiang** [comment]
> When we tried the workflow in our HPC, it encountered multiple errors. One is "Error connecting to https://quay.io". Is it possible to package all necessary tools used in the workflow in a standalone docker? This might be much easier to set up for users. We're planning to buy the Revio so we hope the analyses will be seamless.
> 
> Thanks for considering this feature.

Hi！Nice to meet you!
I am currently trying to run this process on our own HPC. Is it convenient to leave a contact information for communication and exchange?

**Comment by Bin-Guan** [comment]
> Thanks for the suggestion.
> 
> By keeping these images separate, we can more easily update individual components without having to change the code for every task. Also, some tools have incompatible dependencies, so building them into separate containers makes them easier to deploy.
> 
> I think it's likely that the problem you're seeing is caused by the inability of your HPC compute nodes to access the internet. Consolidating into a single image would not solve this issue. There are at least a few solutions:
> 
> * You can set up a private docker container repo within your HPC network, store copies of the containers that you will need for this workflow, and provide the url for this internal repo as `humanwgs.container_registry` in your inputs.json files.
> * If you use miniwdl with singularity (for example, with the miniwdl-slurm plugin), images are downloaded and cached as .sif files on the head node (where the job was launched) and fetched from this cache when they are used.  Since login nodes are typically connected to the internet, this might work for you.
> * If you use Cromwell, there's a tool called [singularity-permanent-cache](https://github.com/biowdl/singularity-permanent-cache) that caches images as .sif files.  You can use `singularity-permanent-cache` to download the containers from a node that can access the internet, then adjust cromwell.conf to use `singularity-permanent-cache` to lookup the file path for the containers.
> 
> If you're looking for help with any of this, please email [support@pacb.com](mailto:support@pacb.com).

Thank you, will try.

**Comment by Bin-Guan** [comment]
> > When we tried the workflow in our HPC, it encountered multiple errors. One is "Error connecting to https://quay.io". Is it possible to package all necessary tools used in the workflow in a standalone docker? This might be much easier to set up for users. We're planning to buy the Revio so we hope the analyses will be seamless.
> > Thanks for considering this feature.
> 
> Hi！Nice to meet you! I am currently trying to run this process on our own HPC. Is it convenient to leave a contact information for communication and exchange?

Sure. My email is bin.guan@nih.gov

**Comment by zhiyu2023** [comment]
Thanks Billy Rowell for nice suggestion , I was running miniwdl with singularity from HPC and got those message "error": "DockerException","message": "Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))", it seems that miniwdl did not connect with singularity .any suggestion ?

**Comment by williamrowell** [comment]
Hi @zhiyu2023.

These questions veer away from specific issues with this workflow and more towards issues with running a WDL workflow in your compute environment.  Please reach out to support@pacb.com and provide the entire miniwdl.log, miniwdl.cfg, and inputs.json file for context.
