### ISSUE TITLE
merge_bam_stats.wdl hist scripts 

### ISSUE THREAD

**Issue by hudja** [PacificBiosciences/HiFi-human-WGS-WDL#138]
Hi,

Panda indexes are incorrect to work with `extract_read_length_and_qual.py` in `bin_length.py` and `bin_quality.py` of `merge_bam_stats.wdl` in v2.0.0-rc1.

Should be:

```
df[0] = pd.cut(df[1], bins=bins, labels=bins.left)
grouped = df.groupby(0)[1].agg(['count', 'sum'])
```

and 

```
df[0] = pd.cut(df[2], bins=bins, labels=bins.left, include_lowest=True)
grouped = df.groupby(0)[1].agg(['count', 'sum'])
```

Best wishes

**Comment by williamrowell** [comment]
Hi @hudja,

Thanks for the bug report.  The indices are correct as provided.  In this new branch, `*.read_length_and_quality.tsv.gz` has an extra column relative to the same file in v1:

1) movie <- new
2) read
3) length
4) quality

**Comment by hudja** [comment]
Thanks! and Sorry, my bad! I am not sure how can I find the latest python scripts for this rc?

https://github.com/PacificBiosciences/wdl-dockerfiles

shows that it was updated 3 months ago.

**Comment by williamrowell** [comment]
No problem.  I moved many (but not all) of the shorter python scripts directly into the WDL code, rather than storing them in the Dockerfiles.  This makes it easier to understand the purpose of a task.  For many v2 steps, you should find the python scripts embedded as heredocs in the task, e.g.:

https://github.com/PacificBiosciences/wdl-common/blob/e03da547ba6c344e7b96325dc4b22ec5e806f026/wdl/tasks/pbmm2.wdl#L74-L85

```
    cat << EOF > extract_read_length_and_qual.py
    import math, pysam
    MAX_QV = 60
    save = pysam.set_verbosity(0)  # suppress [E::idx_find_and_load]
    bamin = pysam.AlignmentFile('~{bam}', check_sq=False)
    pysam.set_verbosity(save)  # restore warnings
    for b in bamin:
      errorrate = 1.0 - b.get_tag("rq")
      readqv = MAX_QV if errorrate == 0 else math.floor(-10 * math.log10(errorrate))
      print(f"{b.query_name.split('/')[0]}\t{b.query_name}\t{len(b.query_sequence)}\t{readqv}")
    bamin.close()
    EOF
```

To find scripts in the v1 releases:

- navigate to the code for the release tag: https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/tree/v1.1.1
- go to the "tool versions and docker images" section of the readme: https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/tree/v1.1.1#tool-versions-and-docker-images
- find the image in which the task runs; in this case, it was the pbmm2 task
- click on the [Dockerfile link](https://github.com/PacificBiosciences/wdl-dockerfiles/tree/3560fcc5a84e044067cea9c9a7669cfc2659178e/docker/pbmm2)
- the scripts were typically in a `scripts` folder like https://github.com/PacificBiosciences/wdl-dockerfiles/tree/3560fcc5a84e044067cea9c9a7669cfc2659178e/docker/pbmm2/scripts

You can see why the heredoc solution is more user friendly.  I'm using it in _almost_ all places where we were using scripts before.  The biggest exceptions are svpack (where the code is already in a git repo, so I can refer to the hash) and the phrank script in tertiary analysis (because it's very long and challenging to read within the task).

**Comment by hudja** [comment]
Yes, I just realized that the extract python script sits in pbmm2 wdl, so deleted my comment! Thank you again!
