### ISSUE TITLE
v2.0.4 on Terra

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#168]
Hi,
Is the family.wdl of v2.0.4 compatible with Terra? The documentation does not explicitly say so. Thanks

**Comment by williamrowell** [comment]
`family.wdl` jobs can be launched in Terra, but because the input contains a custom struct ([`Family family`](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/blob/9bbe28e434878c3b30254c98dcac489a3a656b6e/workflows/humanwgs_structs.wdl#L15-L18)), it doesn't fit easily into the Terra data model and requires loading from an inputs.json ("Upload json") or cutting and pasting the struct into the humanwgs_family -> family field.

`singleton.wdl` has been designed to work better with Terra and the Terra data model.  All inputs have 1:1 key:value mapping (except for the array of hifi_reads), and all outputs have 1:1 key:value mapping.
