### ISSUE TITLE
deepvariant task failure

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#170]
Hi, THe latest version 2.0.5 is getting this error:

[deepvariant](https://job-manager.dsde-prod.broadinstitute.org/jobs/ef685503-d929-4924-8bc3-1726c525b25a)		Task deepvariant.deepvariant_make_examples:6:4 failed. The job was stopped before the command finished. PAPI error code 9. Execution failed: generic::failed_precondition: pulling image: docker pull: running ["docker" "pull" "google/deepvariant:1.6.1"]: exit status 1 (standard error: "failed to register layer: write /usr/local/lib/python3.8/dist-packages/jaxlib/mlir/_mlir_libs/_stablehlo.so: no space left on device\n")

**Comment by williamrowell** [comment]
This is an error directly from GCP, saying that it was unable to pull the docker image because there wasn't enough space on the device.  Did it fail for every `deepvariant_make_examples` task, or just one?

**Comment by gevro** [comment]
All of them

**Comment by gevro** [comment]
Note, this step didn't fail in v2.0.4

**Comment by gevro** [comment]
Some more info: the calculate disk size in these runs was: disk_size = 106 Gb.
The aligned bam was ~45 Gb. 

So I'm not sure why space ran out.

And as mentioned, v2.0.4 ran perfectly fine. I also compared the logs of the input parameters when it ran fine in v2.0.4 vs when it is failing now in v2.0.5, and there is no difference in the input parameters.

So something else must have changed in v2.0.5 that is causing it to fail, and it is not a change in the input parameters or configured disk space.

**Comment by gevro** [comment]
Hi, Curious if any update on this?

**Comment by williamrowell** [comment]
```
generic::failed_precondition: pulling image: docker pull: running ["docker" "pull" "google/deepvariant:1.6.1"]: exit status 1 (standard error: "failed to register layer: write /usr/local/lib/python3.8/dist-packages/jaxlib/mlir/_mlir_libs/_stablehlo.so: no space left on device\n")
```

This error indicates that the GCP compute node ran out of system drive space while trying to pull the Docker image, before any commands in the task are called.  This task hasn't been modified [in weeks](https://github.com/PacificBiosciences/wdl-common/blame/60e9eb5c798b6d35dc26fe8561423cf1dab193bd/wdl/workflows/deepvariant/deepvariant.wdl), and we've had successful runs on GCP as recently as yesterday and Terra+GCP last month, so I think this is likely to be a transient/non-reproducible error.

I would recommend updating to v2.0.7 ([singleton entrypoint on Dockstore](https://dockstore.org/workflows/github.com/PacificBiosciences/HiFi-human-WGS-WDL/HiFi-human-WGS-WDL-singleton:v2.0.7-dockstore?tab=info), [family entrypoint on Dockstore](https://dockstore.org/workflows/github.com/PacificBiosciences/HiFi-human-WGS-WDL/HiFi-human-WGS-WDL-family:v2.0.7-dockstore?tab=info)) because of another fix, but I think this `deepvariant_make_examples` error is transient and will not recur.  If it does recur, I'd recommend reaching out to Terra.

**Comment by gevro** [comment]
Ok 2.0.7 rerun works.
