### ISSUE TITLE
hiphase task failed

### ISSUE THREAD

**Issue by innerpyg** [PacificBiosciences/HiFi-human-WGS-WDL#171]
Hi, I use HiFi-human-WGS-WDL on my HPC

The hiphase version is 0.10.2, the error is as follows:

```
thread '<unnamed>' panicked at 'assertion failed: num_alleles >= num_reads', src/writers/phase_stats.rs:58:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-11-20T02:57:18.231Z ERROR hiphase] Panic detected in ThreadPool, check above for details.
```

There are several samples, but this error occurs only in one sample.
Any comments on this?

**Comment by williamrowell** [comment]
This is likely fixed in newer releases.

If you need consistency with your other samples, the most recent release in the workflow v1 branch is [v1.2.0](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/releases/tag/v1.2.0) with HiPhase v1.4.4.

If you want new features and continued development, the most recent workflow v2 release is [v2.0.7](https://github.com/PacificBiosciences/HiFi-human-WGS-WDL/releases/tag/v2.0.7) with HiPhase v1.4.5.

**Comment by innerpyg** [comment]
Thank you.

I checked the tool version and the options at the same time, referring to your opinion.
I confirmed the --global-realignment-cputime 300 option is deprecated, and removing it solved the problem.
